 name: Zhou Shao Ting
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: pheromone/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: pheromone
            # Text on contribution graph 
            text: pheromone
       - uses: jasineri/simple-push-action@v1
