name: Call Reusable Translate

on:
  push:
    paths:
      - README.md
  workflow_dispatch:

jobs:
  call-translate:
    uses: shaoting0730/shaoting0730/.github/workflows/translate-readme.yml@main
    with:
      file: README.md
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
