name: Translate README

on:
  workflow_call:
    inputs:
      file:
        description: "要翻译的 Markdown 文件路径"
        required: true
        type: string
    secrets:
      OPENAI_API_KEY:
        required: true

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "翻译文件: ${{ inputs.file }}"
