name: Translate README

on:
  workflow_call:
    inputs:
      file: # ✅ 参数名是 file
        description: '要翻译的 Markdown 文件路径'
        required: true
        type: string
    secrets:
      OPENAI_API_KEY:
        required: true

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install openai

      - name: Translate README using OpenAI API
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FILE_PATH: ${{ inputs.file }}
        run: |
          python3 - <<'EOF'
          import os
          from openai import OpenAI

          client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
          file_path = os.getenv("FILE_PATH")

          with open(file_path, "r", encoding="utf-8") as f:
              content = f.read()

          response = client.chat.completions.create(
              model="gpt-4o-mini",
              messages=[
                  {"role": "user", "content": f"请将以下 Markdown 内容翻译成英文，保持格式:\n\n{content}"}
              ]
          )

          translated = response.choices[0].message.content

          output_file = file_path.replace(".md", "_en.md")
          with open(output_file, "w", encoding="utf-8") as f:
              f.write(translated)

          print(f"翻译完成，输出文件: {output_file}")
          EOF
